### ISSUE TITLE
Add an option for auto scrolling whilst dragging

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-draggable-droppable#13]
Need to also be able to pass in a html element which is the scroll container

Logic: scroll when cursor at edge of the screen + drag active. At end of scroll (when mousemove is away from edge of screen) move item by the amount that was moved. Prior art: https://github.com/taye/interact.js/blob/master/src/autoScroll.js

**Comment by mattlewis92** [comment]
Spent a couple hours on this and it was non trivial to implement, may revisit in the future if there is demand for it.

**Comment by MaxiSonntag** [comment]
Could you share your solution to this? Link is outdated.

I already implemented the scroll logic but I'm struggling with the Droppable directive right now, because the drop areas do not change when the container is scrolled via `scrollBy` method. So the content of the container scrolls correctly, but the drop areas remain the same, therefore can't drop on areas that just scrolled into visible area.

Thanks for your help.

**Comment by mattlewis92** [comment]
As of `4.3.0` auto scrolling was implemented: https://github.com/mattlewis92/angular-draggable-droppable/blob/master/CHANGELOG.md#430-2019-04-21 You just need to make sure you add `mwlDraggableScrollContainer` on whichever element is scrollable.

**Comment by MaxiSonntag** [comment]
Figured this out 30 sec before your response, thanks for your response anyway 👍

**Comment by mattlewis92** [comment]
Oh yeah it really should, my bad! Made an issue to track it: https://github.com/mattlewis92/angular-draggable-droppable/issues/94
