### ISSUE TITLE
Allow the end drag if NOT dropped on a mwlDroppable to be animated

### ISSUE THREAD

**Issue by eelcobrolman** [mattlewis92/angular-draggable-droppable#57]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

I'd like to have the div animated (i.e. eased back into the original position) when not dropped on a mwlDroppable.
I tried putting an anim tag on the mwlDraggable div (from @angular/animations), with a "* => void" trigger, but the draggable div just disappears instead of playing the animation.

**Describe your use case for implementing this feature**

For a wordfeud like game, when a stone is not dropped on a valid game board tile, the stone should be moved graceful (i.e. with an ".5s ease") to the rack.

**Additional context**

**Comment by mattlewis92** [comment]
This seems like a reasonable request. Using the animation tag isn't working for you because the lib creates a separate ghost element and does transformations on the which an angular animation wouldn't be able to pick up. The 2 options I can see to do this are:

1/ Set `[ghostDragEnabled]="false"` and then use the `dragStart`, `dragging` and `dragEnd` events to manually move the element as it's being dragged, and you should be able to animate this with angular.

2/ It might be possible for this lib to use the [animation builder](https://angular.io/api/animations/AnimationBuilder) api to animate the element being dragged back. I'm not really sure what a clean API would look like in this case, ideally it would be something that would allow you to pass the animation into the lib so you could customise it fully. Happy to accept a PR here.
